export const infoTableLabels = [
  "Borrower/Lender",
  "Assets",
  "Net Value ($)",
  "Interest Rate (%)",
  "Duration (days)",
];

export const tableData = [
  {
    borrower: "Lend",
    assets: "Samo",
    netvalue: "$1,000,000",
    interestRate: "3%",
    duration: "7days",
  },
  {
    borrower: "Lend",
    assets: "Samo",
    netvalue: "$1,000,000",
    interestRate: "3%",
    duration: "7days",
  },
  {
    borrower: "Lend",
    assets: "Samo",
    netvalue: "$1,000,000",
    interestRate: "3%",
    duration: "7days",
  },
  {
    borrower: "Lend",
    assets: "Samo",
    netvalue: "$1,000,000",
    interestRate: "3%",
    duration: "7days",
  },
  {
    borrower: "Lend",
    assets: "Samo",
    netvalue: "$1,000,000",
    interestRate: "3%",
    duration: "7days",
  },
  {
    borrower: "Lend",
    assets: "Samo",
    netvalue: "$1,000,000",
    interestRate: "3%",
    duration: "7days",
  },
  {
    borrower: "Lend",
    assets: "Samo",
    netvalue: "$1,000,000",
    interestRate: "3%",
    duration: "7days",
  },
  {
    borrower: "Lend",
    assets: "Samo",
    netvalue: "$1,000,000",
    interestRate: "3%",
    duration: "7days",
  },
  {
    borrower: "Lend",
    assets: "Samo",
    netvalue: "$1,000,000",
    interestRate: "3%",
    duration: "7days",
  },
  {
    borrower: "Lend",
    assets: "Samo",
    netvalue: "$1,000,000",
    interestRate: "3%",
    duration: "7days",
  },
  {
    borrower: "Lend",
    assets: "Samo",
    netvalue: "$1,000,000",
    interestRate: "3%",
    duration: "7days",
  },
  {
    borrower: "Lend",
    assets: "Samo",
    netvalue: "$1,000,000",
    interestRate: "3%",
    duration: "7days",
  },
  {
    borrower: "Lend",
    assets: "Samo",
    netvalue: "$1,000,000",
    interestRate: "3%",
    duration: "7days",
  },
  {
    borrower: "Lend",
    assets: "Samo",
    netvalue: "$1,000,000",
    interestRate: "3%",
    duration: "7days",
  },
  {
    borrower: "Lend",
    assets: "Samo",
    netvalue: "$1,000,000",
    interestRate: "3%",
    duration: "7days",
  },
  {
    borrower: "Lend",
    assets: "Samo",
    netvalue: "$1,000,000",
    interestRate: "3%",
    duration: "7days",
  },
  {
    borrower: "Lend",
    assets: "Samo",
    netvalue: "$1,000,000",
    interestRate: "3%",
    duration: "7days",
  },
  {
    borrower: "Lend",
    assets: "Samo",
    netvalue: "$1,000,000",
    interestRate: "3%",
    duration: "7days",
  },
  {
    borrower: "Lend",
    assets: "Samo",
    netvalue: "$1,000,000",
    interestRate: "3%",
    duration: "7days",
  },
  {
    borrower: "Lend",
    assets: "Samo",
    netvalue: "$1,000,000",
    interestRate: "3%",
    duration: "7days",
  },
  {
    borrower: "Lend",
    assets: "Samo",
    netvalue: "$1,000,000",
    interestRate: "3%",
    duration: "7days",
  },
  {
    borrower: "Lend",
    assets: "Samo",
    netvalue: "$1,000,000",
    interestRate: "3%",
    duration: "7days",
  },
  {
    borrower: "Lend",
    assets: "Samo",
    netvalue: "$1,000,000",
    interestRate: "3%",
    duration: "7days",
  },
  {
    borrower: "Lend",
    assets: "Samo",
    netvalue: "$1,000,000",
    interestRate: "3%",
    duration: "7days",
  },
  {
    borrower: "Lend",
    assets: "Samo",
    netvalue: "$1,000,000",
    interestRate: "3%",
    duration: "7days",
  },
  {
    borrower: "Lend",
    assets: "Samo",
    netvalue: "$1,000,000",
    interestRate: "3%",
    duration: "7days",
  },
  {
    borrower: "Lend",
    assets: "Samo",
    netvalue: "$1,000,000",
    interestRate: "3%",
    duration: "7days",
  },
  {
    borrower: "Lend",
    assets: "Samo",
    netvalue: "$1,000,000",
    interestRate: "3%",
    duration: "7days",
  },
];
